// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjpxwyjfzivqehncginq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcHh3eWpmeml2cWVobmNnaW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjQ0ODksImV4cCI6MjA2MzE0MDQ4OX0.neeeqgXdkorGRHAjcLD_TKDQ6PMQf-X-wjlBK5Ot8h8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);